
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package predictatu;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\004\000\002\002\004\000\002\005" +
    "\004\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\006\013\000" +
    "\002\007\011\000\002\010\003\000\002\010\003\000\002" +
    "\011\021\000\002\012\005\000\002\013\006\000\002\014" +
    "\007\000\002\021\003\000\002\021\002\000\002\015\004" +
    "\000\002\015\003\000\002\016\013\000\002\020\003\000" +
    "\002\020\002\000\002\017\003\000\002\017\002\000\002" +
    "\022\003\000\002\022\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\004\004\006\001\002\000\010\005\015\007" +
    "\023\011\020\001\002\000\004\002\012\001\002\000\006" +
    "\024\007\025\011\001\002\000\016\005\uffe8\006\uffe8\007" +
    "\uffe8\011\uffe8\020\uffe8\021\uffe8\001\002\000\010\005\uffff" +
    "\007\uffff\011\uffff\001\002\000\016\005\uffe7\006\uffe7\007" +
    "\uffe7\011\uffe7\020\uffe7\021\uffe7\001\002\000\004\002\001" +
    "\001\002\000\012\002\ufffa\005\ufffa\007\ufffa\011\ufffa\001" +
    "\002\000\012\002\ufffd\005\ufffd\007\ufffd\011\ufffd\001\002" +
    "\000\006\024\007\025\011\001\002\000\006\012\uffe9\021" +
    "\044\001\002\000\012\002\000\005\015\007\023\011\020" +
    "\001\002\000\006\024\007\025\011\001\002\000\012\002" +
    "\ufffc\005\ufffc\007\ufffc\011\ufffc\001\002\000\012\002\ufffb" +
    "\005\ufffb\007\ufffb\011\ufffb\001\002\000\004\010\024\001" +
    "\002\000\004\016\025\001\002\000\004\023\026\001\002" +
    "\000\004\021\027\001\002\000\004\027\030\001\002\000" +
    "\004\020\031\001\002\000\004\025\032\001\002\000\004" +
    "\021\033\001\002\000\006\024\034\025\036\001\002\000" +
    "\010\015\ufff7\017\ufff7\023\ufff7\001\002\000\004\023\037" +
    "\001\002\000\010\015\ufff6\017\ufff6\023\ufff6\001\002\000" +
    "\004\020\040\001\002\000\006\024\034\025\036\001\002" +
    "\000\004\023\042\001\002\000\014\002\uffe9\005\uffe9\007" +
    "\uffe9\011\uffe9\021\044\001\002\000\012\002\ufff5\005\ufff5" +
    "\007\ufff5\011\ufff5\001\002\000\020\002\uffea\005\uffea\006" +
    "\uffea\007\uffea\011\uffea\012\uffea\023\uffea\001\002\000\004" +
    "\020\046\001\002\000\004\026\047\001\002\000\006\012" +
    "\ufff3\021\ufff3\001\002\000\012\002\ufffe\005\ufffe\007\ufffe" +
    "\011\ufffe\001\002\000\004\012\053\001\002\000\012\002" +
    "\ufff4\005\ufff4\007\ufff4\011\ufff4\001\002\000\006\013\054" +
    "\016\ufff0\001\002\000\004\016\ufff1\001\002\000\004\016" +
    "\056\001\002\000\006\021\044\023\uffe9\001\002\000\004" +
    "\023\062\001\002\000\014\002\uffee\005\uffee\007\uffee\011" +
    "\uffee\023\uffee\001\002\000\014\002\ufff2\005\ufff2\007\ufff2" +
    "\011\ufff2\023\062\001\002\000\004\016\063\001\002\000" +
    "\010\022\065\024\uffeb\025\uffeb\001\002\000\006\024\034" +
    "\025\036\001\002\000\006\024\uffec\025\uffec\001\002\000" +
    "\004\023\067\001\002\000\004\020\070\001\002\000\006" +
    "\024\034\025\036\001\002\000\004\023\072\001\002\000" +
    "\016\002\uffe9\005\uffe9\007\uffe9\011\uffe9\021\044\023\uffe9" +
    "\001\002\000\014\002\uffed\005\uffed\007\uffed\011\uffed\023" +
    "\uffed\001\002\000\014\002\uffef\005\uffef\007\uffef\011\uffef" +
    "\023\uffef\001\002\000\006\006\uffe9\021\044\001\002\000" +
    "\004\006\077\001\002\000\004\016\100\001\002\000\004" +
    "\014\101\001\002\000\006\024\034\025\036\001\002\000" +
    "\004\015\112\001\002\000\004\017\104\001\002\000\006" +
    "\024\034\025\036\001\002\000\004\017\106\001\002\000" +
    "\006\024\034\025\036\001\002\000\004\017\110\001\002" +
    "\000\006\024\034\025\036\001\002\000\004\015\ufff8\001" +
    "\002\000\014\002\uffe9\005\uffe9\007\uffe9\011\uffe9\021\044" +
    "\001\002\000\012\002\ufff9\005\ufff9\007\ufff9\011\ufff9\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\006\002\004\005\003\001\001\000\016\003" +
    "\016\004\013\006\020\011\021\012\012\013\015\001\001" +
    "\000\002\001\001\000\004\022\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\022\074\001" +
    "\001\000\004\017\050\001\001\000\014\004\047\006\020" +
    "\011\021\012\012\013\015\001\001\000\004\022\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\034\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\040\001\001\000\002\001\001\000\004\017\042\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\051\001\001\000\002\001\001\000\004\021\054" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\056\001\001\000\006\015\060\016\057\001\001\000\002" +
    "\001\001\000\004\016\073\001\001\000\002\001\001\000" +
    "\004\020\063\001\001\000\004\010\065\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\070\001\001\000\002\001\001\000\004\017\072\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\017\075\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\101\010\102\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\104\001\001\000\002\001\001" +
    "\000\004\010\106\001\001\000\002\001\001\000\004\010" +
    "\110\001\001\000\002\001\001\000\004\017\112\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



  private int xCount = 0;
  private boolean hadX = false;

  public void report_error(String msg, Object info) {
    System.err.println("ERROR: " + msg);
  }
  private void assertMaxX() {
    if (xCount > 4) {
      throw new RuntimeException("Un participante no puede marcar más de 4 (X). Encontradas: " + xCount);
    }
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= archivo EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // archivo ::= enc_camp bloques 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // enc_camp ::= CAMPEONATO nombre 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("CAMPEONATO: " + n); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("enc_camp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloques ::= bloques bloque 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloques",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // bloques ::= bloque 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloques",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloque ::= serie 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // bloque ::= partido_linea 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // bloque ::= participante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // serie ::= SERIE nombre opt_nl EQUIPOS COLON LBRACK cuatro_equipos RBRACK opt_nl 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object list = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 System.out.println("SERIE " + nom + " -> " + list); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("serie",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // cuatro_equipos ::= equipo COMMA equipo COMMA equipo COMMA equipo 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e4left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e4right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + ", " + e2 + ", " + e3 + ", " + e4; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuatro_equipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // equipo ::= IDENT 
            {
              Object RESULT =null;
		 RESULT = IDENT$1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("equipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // equipo ::= QSTRING 
            {
              Object RESULT =null;
		 RESULT = QSTRING$1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("equipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // partido_linea ::= PARTIDO NRO COLON NUMBER NEWLINE DATE DASH QSTRING NEWLINE equipo NUMBER DASH equipo NUMBER opt_nl 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int g1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int g1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer g1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int g2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int g2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer g2 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println("PARTIDO #" + NUMBER$4 + " @ " + QSTRING$8 + " -> "
               + e1 + " " + g1 + " - " + e2 + " " + g2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("partido_linea",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // participante ::= encabezado_participante opt_nl pronos 
            {
              Object RESULT =null;
		 assertMaxX(); xCount = 0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("participante",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // encabezado_participante ::= PARTICIPANTE nombre DASH EMAIL 
            {
              Object RESULT =null;
		int nomleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nomright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String nom = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int mailleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int mailright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String mail = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 System.out.println("PARTICIPANTE: " + nom + " <" + mail + ">"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("encabezado_participante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // pronos ::= PRONOSTICOS opt_partidos COLON opt_nl lista_pronos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("pronos",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // opt_partidos ::= PARTIDOS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_partidos",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // opt_partidos ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_partidos",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // lista_pronos ::= lista_pronos linea_prono 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_pronos",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_pronos ::= linea_prono 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_pronos",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // linea_prono ::= NUMBER COLON opt_x equipo NUMBER DASH equipo NUMBER opt_nl 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int g1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int g1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer g1 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int g2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int g2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer g2 = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println("PRONO " + NUMBER$1 + ": " + e1 + " " + g1 + " - " + e2 + " " + g2
                + (hadX ? " (X)" : "")); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("linea_prono",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // opt_x ::= X 
            {
              Object RESULT =null;
		 hadX = true;  xCount++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_x",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // opt_x ::= 
            {
              Object RESULT =null;
		 hadX = false;              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_x",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // opt_nl ::= NEWLINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_nl",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // opt_nl ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opt_nl",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // nombre ::= IDENT 
            {
              String RESULT =null;
		 RESULT = IDENT$1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // nombre ::= QSTRING 
            {
              String RESULT =null;
		 RESULT = QSTRING$1; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("nombre",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
